### ISSUE TITLE
[Error] Fetch Brand in Products

### ISSUE THREAD

**Issue by aabordalo** [fullstackhero/blazor-wasm-boilerplate#100]
Edit a field with Brand.
![image](https://user-images.githubusercontent.com/95432831/151530459-d9060982-544e-407d-a09e-69b7fb157851.png)

The brand is not selected when Edit form is opened
![image](https://user-images.githubusercontent.com/95432831/151530586-b6a8b039-bdd9-4433-a09c-8a22105602ab.png)

**Comment by iammukeshm** [comment]
I guess it's because the _brands property of the BrandAutoComplete.cs on Initialization is always set to new() List<T>. Because of this Autocomplete doesn't seem to load the respective record.

**Comment by iammukeshm** [comment]
Could you please pull the latest and try again? Also, just FYI, Product Image is also now supported. Please test that too and let me know. Thanks @aabordalo

**Comment by aabordalo** [comment]
It's working.
![image](https://user-images.githubusercontent.com/95432831/151596847-b398f5b9-2f8a-4f82-9c5e-2cc0ab01e8cc.png)
