### ISSUE TITLE
CRUD Operations

### ISSUE THREAD

**Issue by iammukeshm** [fullstackhero/blazor-wasm-boilerplate#11]
Brand CRUD
Product CRUD

Advanced Search Component - Column Wise Search
Export to Excel
Responsive
Pagination Support

**Comment by fretje** [comment]
I don't know why, but in the current implementation of the brands view, the initial search query gets executed twice. It was 3 times actually, but I was already able to remove one of them...

**Comment by 274188A** [comment]
this might fix it https://github.com/fullstackhero/blazor-wasm-boilerplate/pull/47

**Comment by fretje** [comment]
should this be closed already? the search doesn't seem to be fully implemented, also no export to excel...

maybe another issue needs to be created to make this whole thing generic as well...
