### ISSUE TITLE
First Run Issue

### ISSUE THREAD

**Issue by ittyabrehman** [fullstackhero/blazor-wasm-boilerplate#169]
I created a project of blazor wasm using visual studio 2022 and found issues. The logs of the console are added in the log file attached to this issue.

Looking forward to knowing how can I fix this issue
[LOG FILE ](https://github.com/fullstackhero/blazor-wasm-boilerplate/files/8430409/logs.txt)

**Comment by fretje** [comment]
Is this the code straight from the github repository, or did you use the template?

You sure you didn't change/add anything? 

Looking at the log, it seems like you must have a "System" namespace defined somewhere that's conflicting with the global system namespace...

**Comment by ittyabrehman** [comment]
@fretje thanks for having looked at the issue. I created straight away from the template of visual studio.

**Comment by ittyabrehman** [comment]
#170 issue fixed.
