### ISSUE TITLE
notifications are not shown when there are errors in the data of a new user

### ISSUE THREAD

**Issue by jcarlosmanuel** [fullstackhero/blazor-wasm-boilerplate#187]
Hello, congratulations for this amazing project. The issue is when you want to register a new user when clicking on register the page only returns to the login page, but does not show any notification to the user of what happened so that he can know what the error is and can correct them , I also consider that it should not return to the login page if there is an error to give the user the opportunity to correct the errors and not rewrite all the fields again. I don't know if this only happens to me, anyway thanks for your attention. Regards

![register-user](https://user-images.githubusercontent.com/22204487/167699713-fc244bbe-efc0-4802-ab09-e82ede1c0e15.jpg)

![image](https://user-images.githubusercontent.com/22204487/168829251-23dd0697-1c65-476f-bebf-df9ccb18c14d.png)

**Comment by jcarlosmanuel** [comment]
Hello, I think I found a solution, comment the line where a redirection to the login page is made, about the JwtAuthenticationHeaderHandler class, I think that the access control to pages that do not have anonymous access is done from App.razor.
It is not that there is an error in not showing the validations, but that before we can see them the application had already made the redirection to the login page, I consider that this change does not affect the complete operation of the application.

![image](https://user-images.githubusercontent.com/22204487/169385474-25da4f8e-5c2c-43aa-b38e-7a9ef3650c11.png)


![image](https://user-images.githubusercontent.com/22204487/169385522-851a890c-6adb-486a-af3f-7bf95e19084c.png)

**Comment by fretje** [comment]
Ok, I was already thinking it had probably something to do with that... but I commented out the other part (in App.razor) in stead... but that got me nowhere... didn't think about the JwtAuthenticationHeaderHandler...

I see I actually made that change where that navigateTo("/login") happens. GetAccessToken returns null means that the user isn't authenticated, so it should redirect to login in that case...

I think the issue here is rather that the authorization header doesn't need to be set for the "SelfRegister" call, just like it isn't set for the "tokens" calls... so I think the change should be something like

```c#
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        // skip token and self-register endpoints
        if (request.RequestUri?.AbsolutePath.Contains("/tokens") is not true &&
            request.RequestUri?.AbsolutePath.Contains("/self-register") is not true)
        {
            if (await _tokenProviderAccessor.TokenProvider.GetAccessTokenAsync() is string token)
            {
                request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
            }
            else
            {
                _navigation.NavigateTo("/login");
            }
        }

        return await base.SendAsync(request, cancellationToken);
    }
```

Actually it shouldn't be set for any requests that doesn't need the user to be signed in... that also includes the confirm-email, confirm-phone-number and forgot-password calls...

**Comment by jcarlosmanuel** [comment]
Ok, if someone has in the future the need to add an anonymous access page, they would have to add it there, also thinking of someone new to the project, you consider that it is the best way to maintain a simple configuration and maintain the
application security?...

**Comment by fretje** [comment]
Yeah I know... it's not the best way to handle this... It could be generated somehow by examining the swagger.json... or maybe there are other ways... 
It's just that this is now the most pragmatic way... anything else would need some research/design first...

**Comment by jcarlosmanuel** [comment]
perfect, i'll do that, thanks for the help

**Comment by fretje** [comment]
Would you mind creating a PR with that change, once you get it working properly?

**Comment by jcarlosmanuel** [comment]
sure!
