### ISSUE TITLE
Question on Proxy Generation

### ISSUE THREAD

**Issue by kallievz** [fullstackhero/blazor-wasm-boilerplate#209]
Hi. I am currently checking out the wasm Blazor project, added new entitities/controllers using the Api boilerplate.

Now the question is, Blazor project cant see updated proxy, The WebApiClient does not reflect the new controllers?

**Comment by DataTowerSystems** [comment]
See this link https://discord.com/channels/878181478972928011/878182044704841769/926649552482754610

**Comment by fretje** [comment]
You have to run the https://github.com/fullstackhero/blazor-wasm-boilerplate/blob/main/scripts/nswag-regen.ps1 script to update the WebApiClient...

**Comment by kallievz** [comment]
Thanks. Got it...
