### ISSUE TITLE
[BUG] FSH.BlazorWebAssembly.Client.Shared.BaseLayout.SetCurrentTheme - Null Ref while using Azure Auth

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-wasm-boilerplate#26]
While using **AzureAd Auth** I see the error (below)  in the browser tools (so client side wasm) - probably due to the fact we are kind of skip showing thoese controls completely when in AzureAd Auth mode

>blazor.webassembly.js:1         
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MudBlazor.Utilities.MudColor..ctor(String value)
   at MudBlazor.Utilities.MudColor.op_Implicit(String input)
   at FSH.BlazorWebAssembly.Client.Shared.BaseLayout.SetCurrentTheme(ClientPreference themePreference) in C:\Users\274188A\source\repos\CLEAN\WASM\blazor-wasm-boilerplate\src\Client\Shared\BaseLayout.razor.cs:line 49
   at FSH.BlazorWebAssembly.Client.Shared.BaseLayout.OnInitializedAsync() in C:\Users\274188A\source\repos\CLEAN\WASM\blazor-wasm-boilerplate\src\Client\Shared\BaseLayout.razor.cs:line 24
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by fretje** [comment]
I don't see this problem. What are the exact steps to reproduce? Seems to be something with your themepreference? This is something that's stored in local storage. Maybe it still has some stale data from previous versions?

**Comment by 274188A** [comment]
was going to show more detail... but firstly I have to get past this (below) after doing a update of the code base:

>{"source":"DN.WebApi.Infrastructure.Multitenancy.CurrentTenantMiddleware+<InvokeAsync>d__3","exception":"Authentication Failed.","errorId":"7cecd534-cba5-45d0-a90d-b27e4875cdfe","supportMessage":"Provide the ErrorId to the support team for further analysis.","statusCode":401,"succeeded":false}

**Comment by 274188A** [comment]
steps:
1) deleted db, 
2) insert value for Issuer into Tenant eg `https://sts.windows.net/...`
2) set provider to azure on both api and wasm,
3) run api host
4) run wasm

exception shown once log-in negotiations completed
exception shown once log-out completed

![image](https://user-images.githubusercontent.com/40014477/146095811-aa06409e-a797-41ac-bca4-619cc7b37002.png)




3)

**Comment by fretje** [comment]
Have you checked your local storage? I bet there's a null value there somewhere in your themepreference which shouldn't be there...

**Comment by 274188A** [comment]
yeah - that was it - working ok now.   I do get another exception - but I should probably close this and raise another.
![image](https://user-images.githubusercontent.com/40014477/146096584-2f39ee2d-29bc-4f1d-a2f1-fe7414e0443c.png)

**Comment by fretje** [comment]
There might be a bug somewhere how that null value got there in the first place (if it's not from doing some strange debugging stuff), but has nothing to do with AzureAd... ;-)

**Comment by fretje** [comment]
And that error message is probably fine... I think the signalr client always probes first without credentials, and only sends them after a 401 received.
