### ISSUE TITLE
Permission Management for Role

### ISSUE THREAD

**Issue by iammukeshm** [fullstackhero/blazor-wasm-boilerplate#46]

**Comment by PedroVentura235** [comment]
Hi, is someone already implementing this one? I can start with it

**Comment by iammukeshm** [comment]
@PedroVentura235 you can start with it. Let me know

**Comment by iammukeshm** [comment]
@PedroVentura235  can we close this? or do we have more changes needed for this?

**Comment by iammukeshm** [comment]
@PedroVentura235 i was checking this, seems like after logging in as an Admin , I am able to modify the permissions of the Admin Role. I think it's better to disable that. Nobody should be able to modify an Admin's Permission and Admin roles by default should get all the available permission.
