### ISSUE TITLE
Improve Search Integration

### ISSUE THREAD

**Issue by iammukeshm** [fullstackhero/blazor-wasm-boilerplate#53]
Implement better search on CRUD pages to take advantage of Advanced Search via FSH API.

**Comment by iammukeshm** [comment]
@fretje this is already done, right?

**Comment by fretje** [comment]
Yes, ServerEntityTableContext constructor now also takes an enableAdvancedSearch boolean which you can set to true to automatically generate "advanced search on columns". It takes the columns from the EntityFields array (SortLabel) for that.

Advanced search filtering has to be implemented per type. An example has been implemented on the products view. Filtering on specific brand, or within specific min- and maxrates.
