### ISSUE TITLE
Drop-Down blur 

### ISSUE THREAD

**Issue by 274188A** [fullstackhero/blazor-wasm-boilerplate#74]
While creating a new Product a user selects from the dropdown the brand for the product.
Before saving, the user changes their mind and selects another brand.

**Expected**: User can select another Brand from the drop-down then proceed to save.
**Actual**: User is unable to select any other option from the drop-down due to the disabling in the css

**Comment by 274188A** [comment]
![74](https://user-images.githubusercontent.com/40014477/148156875-81b55f92-039d-43ca-abe4-050d97d80e4e.gif)

**Comment by iammukeshm** [comment]
I guess you might have to clear the `Samsung` text and enter a new keyword to start searching. It's an autocomplete implementation

**Comment by 274188A** [comment]
Ok I see, I think the blur put me off - see below:
![image](https://user-images.githubusercontent.com/40014477/148308805-f189d464-5e3c-4c7c-8df0-b0568543c137.png)
the blur effect is actually obscuring the user from seeing the text they type (while re-selecting).
Is there a way to not blur the dropdown (list + textbox)?

**Comment by iammukeshm** [comment]
Fixed. Please Clear the Cache or try in Incognito Mode and let me know. Closing the issue for now.

**Comment by 274188A** [comment]
yip all good - thx
