### ISSUE TITLE
Misundestrand with the Architecture

### ISSUE THREAD

**Issue by anasseb** [fullstackhero/blazor-wasm-boilerplate#80]
Hello,

I don't understand the architecture of the project, where are the controllers and connection string ?
Can you please can you enlighten me ?
Thanks

**Comment by matthewcorven** [comment]
@anasseb this is the frontend project.  Backend is here: https://github.com/fullstackhero/dotnet-webapi-boilerplate

**Comment by anasseb** [comment]
@matthewcorven Thank you very much sir
