### ISSUE TITLE
ApiHelper.ExecuteCallGuardedAsync cannot catch exception

### ISSUE THREAD

**Issue by xlogex** [fullstackhero/blazor-wasm-boilerplate#81]
Cannot show snackbar message

**Comment by xlogex** [comment]
![image](https://user-images.githubusercontent.com/27079402/149434244-81024a98-d994-445d-90f3-91dc894c3f67.png)

**Comment by xlogex** [comment]
![image](https://user-images.githubusercontent.com/27079402/149435118-1a8c3cf4-e770-455a-8051-e3b96cff7158.png)

**Comment by xlogex** [comment]
solution:
![image](https://user-images.githubusercontent.com/27079402/149438859-613c12c1-bf80-46bd-b849-2ea15ad35e58.png)

**Comment by fretje** [comment]
This is a problem with the server side rather than the client side... when/how exactly do you get there? 

This should get catched by the `ApiException<ErrorResult>` block... if it's not then that is the problem needed to be fixed... not adding another catch block here...
