### ISSUE TITLE
Move Dense, Bordered and Striped to the ThemeManager Pane

### ISSUE THREAD

**Issue by fretje** [fullstackhero/blazor-wasm-boilerplate#91]
Having those 3 switches on every table is a sore on the eye (it makes the first column wider than it has to be and it's totally messed up when the first column isn't wide enough anymore).

I think these would fit perfectly in the ThemeManager SidePanel as user-configurable global settings for all the tables in the app (at least those that subscribe to the changes of those properties)

**Comment by iammukeshm** [comment]
Yeah, I have actually tried this earlier. But the issue is after storing these values to localStorage (like other settings), how do we make the table component retrieve and refresh these changes.

**Comment by fretje** [comment]
Hmm jep... I didn't say it was gonna be easy :-D

I'm sure there must be a way... isn't this what blazor is all about? ;-)

Maybe we should post the question on the mudblazor repo or discord...

**Comment by iammukeshm** [comment]
Probably can be a mix of EventCallBack and CascadingParams. Will try.

**Comment by fretje** [comment]
waj on discord mentioned something that might be interesting;

> have a look at this https://github.com/aksoftware98/blazor-utilities 
> we can subscribe to get updates on theme settings
>

**Comment by iammukeshm** [comment]
Do review this. May require minor cleanups
