### ISSUE TITLE
Login remember me support?

### ISSUE THREAD

**Issue by dotnetshadow** [fullstackhero/blazor-wasm-boilerplate#96]
Hi there, 

Any chance of implementing the remember me for the Login? Not sure how the jwt and cookie thing would work in order to support this?

Cheers

**Comment by fretje** [comment]
This is already supported out of the box. The tokens are stored in localstorage and automatically renewed when necessary. That remember me checkbox is not necessary, as it's on by default, and I wouldn't know how to put it off, other than not storing the refresh token maybe, but that would make you have to log in again every hour...

**Comment by iammukeshm** [comment]
The 'Remember Me' Check box looks irrelevant since we already have a refresh mechanism. Will remove it from the login component.
